reconstruction flow
compound-eye/3DVideos2Stereo pull request #2
Opened 2021-06-05 20:11 UTC by vishrutg

2021-06-06 02:06 UTC, yqsony commented on reconstructionFlow.py
> +import scripts.analysis.image_utils
Are these two utils in this repo?

2021-06-06 02:06 UTC, yqsony commented on reconstructionFlow.py
> +#     exr_util.save(path, img)
Are these still needed?

2021-06-07 04:03 UTC, vishrutg commented on reconstructionFlow.py
> +import scripts.analysis.image_utils
no but the script that will call this python script will set the `PYTHONPATH` appropriately

2021-06-07 04:03 UTC, vishrutg commented on reconstructionFlow.py
> +#     exr_util.save(path, img)
removed

2021-06-07 06:10 UTC, yqsony requested changes

2021-06-07 06:10 UTC, yqsony commented on reconstructionFlow.py
> +def forward_flow_to_backward_flow(forward, ignore_value=-1):
We are now using -32767 as an ignore value for flow. -1 might not be safe for flow values. We can import the constant.py.

2021-06-07 06:10 UTC, yqsony commented on reconstructionFlow.py
> +    os.system(command)
It would be better to use `subprocess` so we can catch it when a command failed.

```python
p = subprocess.Popen(cmds, cwd=working_dir, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=False)       
out, err = p.communicate() 
ret_code = p.returncode   # ret_code != 0, indicates an error occured in execution.        
if ret_code:            
    logging.error(err)            
    return False       
logging.info(out)
```

2021-06-16 06:52 UTC, vishrutg commented on reconstructionFlow.py
> +    os.system(command)
this is fixed

2022-08-25 05:19 UTC, closed without merging